# Generated by Django 5.0.1 on 2024-01-28 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='idSpecialties',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.specialties'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('idGroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.group')),
            ],
        ),
    ]
