# Generated by Django 5.0.1 on 2024-01-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_group_idspecialties_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='idSpecialties',
        ),
        migrations.RemoveField(
            model_name='student',
            name='idGroup',
        ),
        migrations.DeleteModel(
            name='Specialties',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
