# Generated by Django 5.0.1 on 2024-02-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolleeprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='changeDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='studentcard',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
