# Generated by Django 5.0.1 on 2024-02-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_document_copypassport_alter_document_copysnils_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolleeprofile',
            name='code',
            field=models.IntegerField(default=None),
        ),
    ]
