# Generated by Django 5.0.1 on 2024-02-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_enrolleeprofile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolleeprofile',
            name='code',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
