# Generated by Django 5.0.1 on 2024-02-06 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_enrollee_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcard',
            name='idEnrollee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.enrollee'),
        ),
    ]
