# Generated by Django 5.0.1 on 2024-02-06 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_studentcard_idenrollee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='idDocument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.document'),
        ),
    ]
