# Generated by Django 5.0.1 on 2024-02-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_enrollee_idenrolleeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='middleName',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enrolleeprofile',
            name='phone',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
