# Generated by Django 5.0.1 on 2024-02-06 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_enrollee_middlename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='idDocument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.document'),
        ),
    ]
