# Generated by Django 5.0.1 on 2024-02-06 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_enrollee_idenrolleeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollee',
            name='idEnrolleeProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.enrolleeprofile'),
        ),
    ]
