# Generated by Django 5.0.1 on 2024-02-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_enrollee_iddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentboard',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
