# Generated by Django 5.0.1 on 2024-02-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_alter_studentboard_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardhistory',
            name='comment',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='cardhistory',
            name='field',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='changeData',
            field=models.TextField(null=True),
        ),
    ]
