# Generated by Django 5.0.1 on 2024-02-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_cardhistory_comment_cardhistory_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistory',
            name='changeDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
