# Generated by Django 5.0.1 on 2024-02-27 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_alter_cardhistory_changedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistory',
            name='changeDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
