# Generated by Django 5.0.1 on 2024-02-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_alter_cardhistory_changedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistory',
            name='changeDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
