# Generated by Django 5.0.1 on 2024-03-03 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_alter_cardhistory_changedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistory',
            name='idUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='crm.user'),
        ),
    ]
