# Generated by Django 5.0.1 on 2024-03-12 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_alter_cardhistory_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timeLiveToken',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.BooleanField(default=False),
        ),
    ]
