# Generated by Django 5.0.1 on 2024-03-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_user_timelivetoken_user_token_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timeLiveToken',
            field=models.DateTimeField(null=True),
        ),
    ]
