# Generated by Django 5.0.1 on 2024-03-13 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_alter_user_timelivetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardhistory',
            name='changeDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 16, 19, 13, 241226)),
        ),
    ]
